from __future__ import annotations

from pydantic import BaseModel, Field
from pathlib import Path
from typing import TypedDict
import json
import sys
import os

from langchain_openai import ChatOpenAI
from langgraph.graph import END, START, StateGraph
from verdict_log import verdict_logs

# ─────────────────────────────────────────────
#     Env variables
# ─────────────────────────────────────────────

JSON_FILE = os.getenv("JSON_FILE")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# ─────────────────────────────────────────────
#     Shared states
# ─────────────────────────────────────────────

class ReasoningInfo(BaseModel):
    """Reasoned information about log sequence"""
    normal: bool = Field(description="Ture if log sequence is normal, False otherwise")
    reasoning: str = Field(description="Reason for classification")

class AgentState(TypedDict):
    raw_input: list[str]
    raw_output: list[str]
    analysis: list[str]
    reasoning: list[str]

# ─────────────────────────────────────────────
#     1. Node: analyse log sequence
# ─────────────────────────────────────────────

model1 = ChatOpenAI(model="gpt-5-nano")

def _create_prompt_for_analysis(log_sequence: str) -> str:
    return (f"""
        You are Node 1 in an agentic AI pipeline. Your specific task is to analyze and describe parsed log sequences. 

        INPUT: 
        You will receive a parsed log sequence formatted as a single line of comma-separated values.
        
        YOUR OBJECTIVE:
        Translate the sequence of log events into a clear, chronological narrative. Describe what operational or technical processes are occurring step-by-step based on the sequence provided.
        
        STRICT CONSTRAINTS:
        1. NO OUTCOMES OR CLASSIFICATIONS: You are an observer, not a judge. Do not state or imply whether the sequence is "normal," "abnormal," "anomalous," "expected," "suspicious," or "malicious." Leave all evaluations and conclusions to downstream nodes. Just describe what is happening.
        2. PLAIN TEXT ONLY: Output your analysis strictly as continuous plain text prose (a standard paragraph). Do not use any structural formatting, including JSON, YAML, bullet points, numbered lists, or headers.
    
        INPUT SEQUENCE: {log_sequence}
    """).strip()

def analyze_logs(state: AgentState) -> AgentState:
    for loo_sequence in state.get("raw_input"):
        prompt: str = _create_prompt_for_analysis(loo_sequence)
        answer = model1.invoke(prompt)
        state["analysis"].append(answer.content)
    return state

# ─────────────────────────────────────────────
#     2. Node: Reason log sequence
# ─────────────────────────────────────────────

model2 = ChatOpenAI(model="gpt-5-nano")
model_with_structured_output = model2.with_structured_output(ReasoningInfo)

def _create_prompt_for_reasoning(log_sequence: str, analysis: str) -> str:
    return (f"""
        You are Node 2 in an agentic AI security and operations pipeline. Your task is to evaluate system logs to detect anomalies.

        INPUTS:
        1. Parsed Log Sequence: A raw, comma-separated list of log events.
        2. Sequence Analysis: An objective, step-by-step narrative of what occurred, generated by a previous node.
        
        YOUR OBJECTIVE:
        Analyze the provided inputs and determine if the sequence of events represents normal system behavior or abnormal/anomalous behavior. 
        
        EVALUATION GUIDELINES:
        - Consider a sequence ABNORMAL if it contains evidence of:
          - Repeated failures (e.g., brute-force attempts, crash loops).
          - Unexpected operational orders (e.g., attempting to read a file before opening it).
          - Unauthorized access patterns or critical system errors.
        - Consider a sequence NORMAL if the events follow a logical, expected operational flow (e.g., login -> request -> process -> logout) even if minor, routine warnings occur.
        - Base your decision strictly on the provided sequence and analysis. Do not invent context.
        
        OUTPUT INSTRUCTIONS:
        You will output your findings using the provided structured format. 
        - For the 'normal' boolean field: Return true for expected behavior, false for anomalies.
        - For the 'reasoning' string field: Provide a concise, logical justification for your decision. Cite specific events from the log sequence or analysis that drove your conclusion.
    
        INPUT LOG SEQUENCE: {log_sequence}
        LOG SEQUENCE ANALYSIS: {analysis}
    """).strip()

def reasoning_logs(state: AgentState) -> AgentState:
    if len(state.get("raw_input")) != len(state.get("analysis")):
        raise RuntimeError("Node 2: len(raw_input) != len(analysis). Something went wrong!")

    raw_input = state.get("raw_input")
    analysis = state.get("analysis")

    for i in range(len(raw_input)):
        prompt: str = _create_prompt_for_reasoning(raw_input[i], analysis[i])
        answer = model_with_structured_output.invoke(prompt)
        parsed_answer = f"{"normal" if answer.normal else "abnormal"} - {answer.reasoning}"
        state["reasoning"].append(parsed_answer)
    return state

# ─────────────────────────────────────────────
#     Build the LangGraph
# ─────────────────────────────────────────────

def build_graph() -> StateGraph:
    graph = StateGraph(AgentState)

    graph.add_node("analyze_logs", analyze_logs)
    graph.add_node("reasoning_logs", reasoning_logs)

    graph.add_edge(START, "analyze_logs")
    graph.add_edge("analyze_logs", "reasoning_logs")
    graph.add_edge("reasoning_logs", END)

    return graph.compile()

def main() -> None:

    input_path = Path(JSON_FILE)
    if not input_path.exists():
        print(f"ERROR: '{input_path}' not found.", file=sys.stderr)
        sys.exit(1)

    with open(input_path, encoding="utf-8") as f:
        raw_json: list[dict] = json.load(f)

    raw_json = raw_json[:]
    dataset_length = len(raw_json)

    print(f"Loaded {len(raw_json)} entries from {input_path}")

    # ── Build and run the graph ──
    app = build_graph()

    initial_state: AgentState = {
        "raw_input": [log_dict.get("input") for log_dict in raw_json],
        "raw_output": [log_dict.get("output") for log_dict in raw_json],
        "analysis": [],
        "reasoning": []
    }

    final_state = app.invoke(initial_state)

    verdicts: list[str] = []
    for i in range(dataset_length):
        verdict: str = verdict_logs(final_state["raw_output"][i], final_state["reasoning"][i])
        verdicts.append(verdict)

    with open("results.json", "w", encoding="utf-8") as f:
        # Exclude raw_entries from output to keep it tidy
        output = []
        for i in range(dataset_length):
            output.append({
                "input": final_state["raw_input"][i],
                "output": final_state["raw_output"][i],
                "analysis": final_state["analysis"][i],
                "reasoning": final_state["reasoning"][i],
                "verdict": verdicts[i]
            })
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"\nResults saved to results.json")

if __name__ == "__main__":
    main()